# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :deployToTestFlight do
        build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
        upload_to_testflight(
          skip_waiting_for_build_processing: true,
          apple_id: "APPLE_ID",
          itc_provider: "3GJNX7FF3F"
        )
        get_certificates
        get_provisioning_profile
    end 
end
