# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :deployToInternal do
    //flutter build appbundle
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
      track: 'internal',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deployToProd do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
